In [13]:
#np_array vs list
import numpy as np

# 0~10 2씩 증가하는 수열

series =list(range(0,11,2))
print(series)

numpy_series = np.array(series)
print(numpy_series) # ','가 없다

[0, 2, 4, 6, 8, 10]
[ 0  2  4  6  8 10]


In [5]:
numpy_array = np.arange(0,11,2) # arange(start, stop, step) // range() 와 동일하 method
print(numpy_array)

[ 0  2  4  6  8 10]


In [6]:
# 0~1 0.2 씩 증가하는 수열
try:
  list1 = list(range(0,1,0.2))
  print(list1)
except Exception as e:
  print("넘파이 매개 변수에는 정수만 가능하다", e)

넘파이 매개 변수에는 정수만 가능하다 'float' object cannot be interpreted as an integer


In [14]:
arr2 = np.arange(0,1,0.2)
print(arr2) # arange 매개변수는 실수 전체 가능

[0.  0.2 0.4 0.6 0.8]


In [17]:
a = np.linspace(0.0, 1.1, 5)
print(a) # 0~1.1까지 5개로 분할

[0.    0.275 0.55  0.825 1.1  ]


In [19]:
# Numpy array 는 brodcasting 연산이 가능하다. (병렬 처리)

list_plus = list(range(6))
print(list_plus)

list_plus = list_plus + [6,]
print(list_plus)

# list() +연산자는 concatenate기능을 한다.

[0, 1, 2, 3, 4, 5]
[0, 1, 2, 3, 4, 5, 6]


In [31]:
# Numpy array는 병렬처리를 통한 스칼라 계산이 가능하다.

numpy_array = np.arange(6)
print(numpy_array)

print(numpy_array + 5)
print(numpy_array - 5)
print(numpy_array * 5)
print(numpy_array / 5)

[0 1 2 3 4 5]
[ 5  6  7  8  9 10]
[-5 -4 -3 -2 -1  0]
[ 0  5 10 15 20 25]
[0.  0.2 0.4 0.6 0.8 1. ]


In [29]:
# 두 넘파이 배열의 열 크기가 맞으면 병렬 연산이 가능하다.
numpy_array2 = np.array([[1,2,3],[4,5,6]])
print(numpy_array2,"\n")
print(numpy_array2 + [10,20,30]) # shape가 (,3)인 넘파이 배열을 (1,3)으로 바꾸고 1인 차원에서 값을 병렬처리

[[1 2 3]
 [4 5 6]] 

[[11 22 33]
 [14 25 36]]


In [30]:
# 두 넘파이 배열은 차원은 같으나 배열의 형태가 다르다.
print(np.ndim(numpy_array2), np.ndim(np.array([10,20,30]).reshape(1,3)))

2 2


In [32]:
# 넘파이 배열 초기화 np.zeros(), np.ones()

zero_array = np.zeros(10) # 1*10 배열 생성, 0.0 으로 초기화한다.
print(zero_array)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [34]:
# 3*4 배열 1 로 초기화

one_arr = np.ones([3,4],dtype=int)
print(one_arr)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [35]:
# 넘파이 배열의 속성 shpae(배열 모양), size(배열 요소 갯수), ndim(차원의 수) dtype( 배열 자료형 )

print(one_arr.shape)
print(one_arr.size)
print(one_arr.ndim)
print(one_arr.dtype)

(3, 4)
12
2
int64


In [37]:
# indexing: idx로 배열 데이터 접근 arr[0] arr[1]
# slicing: 배열의 부분 요소 뽑아내기 arr[start:end]

arr = np.arange(10)
print(arr)

# indexing
print(arr[1])

# slicing
print(arr[3:6]) # start ~ end-1

print(arr[:])

print(arr[3:])

print(arr[:7])

[0 1 2 3 4 5 6 7 8 9]
1
[3 4 5]
[0 1 2 3 4 5 6 7 8 9]
[3 4 5 6 7 8 9]
[0 1 2 3 4 5 6]


In [38]:
# boolean indexing (filter 역할)

bool_index = arr > 5 # 5 초과의 요소에 True를 주는 넘파이 어레이

print(bool_index)

print(arr[bool_index])

[False False False False False False  True  True  True  True]
[6 7 8 9]


In [40]:
# 배열의 변형 방법 transpose() 전치행렬
# reshape() 행렬의 shape 바꾸기
# flatten() 1차원 축소

numpy_array3 = np.array([[1,2,3],[4,5,6]])

print(numpy_array3,"\n", numpy_array3.shape)

[[1 2 3]
 [4 5 6]] 
 (2, 3)


In [42]:
numpy_array3_transpose = numpy_array3.transpose()

print(numpy_array3_transpose)

print(numpy_array3_transpose.shape)

[[1 4]
 [2 5]
 [3 6]]
(3, 2)


In [49]:
f_arr = np.ones([3,4,5], dtype=int)
print(f_arr)
f_arr = np.arange(1, f_arr.size + 1).reshape(f_arr.shape)
print(f_arr.ndim, "\n", f_arr)


[[[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]

 [[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]

 [[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]]
3 
 [[[ 1  2  3  4  5]
  [ 6  7  8  9 10]
  [11 12 13 14 15]
  [16 17 18 19 20]]

 [[21 22 23 24 25]
  [26 27 28 29 30]
  [31 32 33 34 35]
  [36 37 38 39 40]]

 [[41 42 43 44 45]
  [46 47 48 49 50]
  [51 52 53 54 55]
  [56 57 58 59 60]]]


In [48]:
# 3차원 배열을 1차원으로 축소

f_arr_flatten = f_arr.flatten()
print(len(f_arr_flatten))
print(f_arr_flatten)

60
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49 50 51 52 53 54 55 56 57 58 59 60]


In [54]:
# reshape(-1,N) 행 크기로 -1이 주어졌다. 배열을 변형할때 열크기를 맞추고 행크기를 정한다.
# reshape 전후로 배열의 size는 동일하게 행 크기를 경정한다.

arr = np.arange(12)
print(arr)

arr_1_12 = arr.reshape(1,12)
print(arr_1_12) # 대괄호가 하나 더 생긴다.

arr_2_6 = arr.reshape(2,6)
print(arr_2_6)

arr_3_4 = arr.reshape(3,4)
print(arr_3_4)

#error
try:
  arr12_45 = arr.reshape(12,45)
except Exception as e:
  print("size가 다르게 변형할 수 없다.",e)

try:
  arr_0_5_24 = arr.reshape(0.5,24)
except Exception as e:
  print("배열의 형태는 정수만 가능하다" , e)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2  3  4  5  6  7  8  9 10 11]]
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
size가 다르게 변형할 수 없다. cannot reshape array of size 12 into shape (12,45)
배열의 형태는 정수만 가능하다 'float' object cannot be interpreted as an integer


In [59]:
# 행의 크기를 고정하지 않는 경우(-1)
arr_negative_1 = arr.reshape(-1,1)
print(arr_negative_1.shape)
print(arr_negative_1)


arr_negative_3 = arr.reshape(-1,3)
print(arr_negative_3.shape)
print(arr_negative_3)

arr_negative_6 = arr.reshape(-1,6)
print(arr_negative_6.shape)
print(arr_negative_6)

arr_negative_12 = arr.reshape(-1,12)
print(arr_negative_12.shape)
print(arr_negative_12)

(12, 1)
[[ 0]
 [ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]]
(4, 3)
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
(2, 6)
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]
(1, 12)
[[ 0  1  2  3  4  5  6  7  8  9 10 11]]


In [60]:
import pandas as pd

In [62]:
# dataframe 만들기 ( list나 dictinary를 dataframe으로 만들 수 있다 )

list2df = [["Kim",30,90],["lee",25,98],["park",19,87]]
df = pd.DataFrame(list2df)
df

0   1   2
0   Kim  30  90
1   lee  25  98
2  park  19  87

In [63]:
df.columns = ("name", "age", "score") # list or tuple, columns 이름 할당
df

name  age  score
0   Kim   30     90
1   lee   25     98
2  park   19     87

In [64]:
df.index = ['one', 'two', 'three'] # index name 할당

df

name  age  score
one     Kim   30     90
two     lee   25     98
three  park   19     87

In [66]:
# 데이터 받기

df_csv = pd.read_csv("/content/drive/MyDrive/AIML_bum/2we/data.csv", encoding="UTF-8")
df_csv

name   age   score
0   Kim    27      92
1   Lee    33      98
2  Park    19      87

In [67]:
df_xlsx = pd.read_excel("/content/drive/MyDrive/AIML_bum/2we/data.xlsx")
df_xlsx

반   이름 성별    국어     수학 응시여부 확인여부
0  A반  구이서  남  90.0   89.0   응시   확인
1  B반  김이정  여  78.0   45.0   응시   확인
2  A반  오지수  남   NaN    NaN   응시   확인
3  B반  김선후  남  33.0   44.0   응시  NaN
4  A반  하진희  여   0.0   85.0   응시  NaN
5  A반  강현진  남   NaN    NaN  NaN  NaN
6  B반  김진솔  남  90.0   89.0   응시   확인
7  B반  박서준  여  78.0   45.0   응시   확인
8  A반  김성희  남   NaN    NaN  NaN   확인
9  B반  이지서  여  86.0  100.0   응시   확인

In [70]:
df_xlsx.info() # null 정보를 통해 이상치, 결측치를 확인 할 수 있다. 유사한 특성의 그룹의mean 계산을 통해 이 부분을 해결할 수 있다

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 7 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   반       10 non-null     object 
 1   이름      10 non-null     object 
 2   성별      10 non-null     object 
 3   국어      7 non-null      float64
 4   수학      7 non-null      float64
 5   응시여부    8 non-null      object 
 6   확인여부    7 non-null      object 
dtypes: float64(2), object(5)
memory usage: 688.0+ bytes


In [69]:
df_xlsx.head()

반   이름 성별    국어    수학 응시여부 확인여부
0  A반  구이서  남  90.0  89.0   응시   확인
1  B반  김이정  여  78.0  45.0   응시   확인
2  A반  오지수  남   NaN   NaN   응시   확인
3  B반  김선후  남  33.0  44.0   응시  NaN
4  A반  하진희  여   0.0  85.0   응시  NaN

In [71]:
df_xlsx.tail()

반   이름 성별    국어     수학 응시여부 확인여부
5  A반  강현진  남   NaN    NaN  NaN  NaN
6  B반  김진솔  남  90.0   89.0   응시   확인
7  B반  박서준  여  78.0   45.0   응시   확인
8  A반  김성희  남   NaN    NaN  NaN   확인
9  B반  이지서  여  86.0  100.0   응시   확인

In [73]:
df_xlsx[["국어"]] # 1차원 데이터

국어
0  90.0
1  78.0
2   NaN
3  33.0
4   0.0
5   NaN
6  90.0
7  78.0
8   NaN
9  86.0

In [74]:
df_xlsx[["국어","수학"]]

국어     수학
0  90.0   89.0
1  78.0   45.0
2   NaN    NaN
3  33.0   44.0
4   0.0   85.0
5   NaN    NaN
6  90.0   89.0
7  78.0   45.0
8   NaN    NaN
9  86.0  100.0

In [77]:
#unique(), 데이터의 유일한 값을 뽑아올 수 있다.
df_xlsx["성별"].unique() # 리스트를 안넣어도 데이터에 접근 가능

array(['남', '여'], dtype=object)